sudo: required

language: bash

before_install:
  - wget https://releases.hashicorp.com/terraform/0.11.8/terraform_0.11.8_linux_amd64.zip
  - sudo unzip -o -d /usr/local/bin terraform_0.11.8_linux_amd64.zip
  - terraform version


script:
  - ENV=test make init
  - ENV=test make validate
